### ISSUE TITLE
What are the correct dates for the conference ?

### ISSUE THREAD

**Issue by jbampton** [BaseMax/CACNA2023Event#6]
From the English homepage:

https://cacna2023.kashanu.ac.ir/en/

<img width="737" alt="Screen Shot 2023-04-06 at 10 09 58 pm" src="https://user-images.githubusercontent.com/418747/230375562-f8218386-1597-4189-bf97-3054b5b17753.png">

**Comment by BaseMax** [comment]
Thanks, it's a good point. where is the PR?
